name: Run test suite

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: tac        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: |
          server/package-lock.json
          client/package-lock.json
          shared/package-lock.json
    - name: Install shared modules
      run: |
        cd shared
        npm ci
    - name: Linting shared
      run: |
        cd shared
        npm run lint
    - name: Install server modules
      run: |
        cd server
        npm ci
    - name: Check linting and formatting of server
      run: |
        cd server
        npm run lint
        npm run prettier-check
    - name: Build server documentation
      run: |
        cd server
        npm run building
    - name: Run typescript build
      run: |
        cd server
        npm run tsc
    - name: Check Locale Files (All languages and identical keys)
      run: |
        cd server
        npm run checkLocales
    - name: Install client modules
      run: |
        cd client
        npm ci
    - name: Run client lint
      run: |
        cd client
        npm run lint
    - name: Run client tsc
      run: |
        cd client
        npm run tsc
    - name: Build Vue Files
      run: |
        cd client
        npm run build
    - name: Run server test
      run: |
        cd server
        npm run test -- --coverage=false
      env:
        paypal_Secret: ${{ secrets.PAYPAL_SECRET }}
